version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: my-lambda-infra-stack-MyHelloWorldFunction-ryC0JrebbF7Z  # <-- Lambda function name
        Alias: live                   # <-- alias for traffic shifting