AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # The Lambda Function
  MyHelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./deployment.zip  # Use a dummy placeholder
      AutoPublishAlias: live      # SAM creates and manages the 'live' alias

  # CodeDeploy Application - Manages deployments for this app
  MyCodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Lambda

  # CodeDeploy Deployment Group - Defines HOW to deploy
  MyCodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref MyCodeDeployApplication
      ServiceRoleArn: arn:aws:iam::686255975873:role/codedeploy # You need to create this role
      DeploymentConfigName: CodeDeployDefault.LambdaCanary10Percent5Minutes
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL

  # # IAM Role for CodeDeploy
  # CodeDeployServiceRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service: codedeploy.amazonaws.com
  #           Action: sts:AssumeRole
  #     ManagedPolicyArns:
  #       - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda

Outputs:
  FunctionName:
    Description: "Lambda Function Name"
    Value: !Ref MyHelloWorldFunction
  CodeDeployApp:
    Description: "CodeDeploy Application Name"
    Value: !Ref MyCodeDeployApplication
  CodeDeployDeploymentGroup:
    Description: "CodeDeploy Deployment Group Name"
    Value: !Ref MyCodeDeployDeploymentGroup